name: Automatic Update stockpick

# Mengatur jadwal otomatisasi alur kerja pipa CI/CD
on:
  schedule:
    # Berjalan otomatis setiap hari Senin sampai Jumat pukul 09:30 UTC
    # 09:30 UTC sama dengan pukul 16:30 WIB (Tepat setelah pasar bursa IHSG ditutup resmi)
    - cron: '30 9 * * 1-5'
  workflow_dispatch: # Mengaktifkan tombol manual "Run workflow" di tab Actions GitHub

jobs:
  screen-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Mengambil seluruh riwayat commit agar sinkronisasi Git berjalan mulus

      - name: Post Set Up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Prebuilt TA-Lib & Dependencies
        run: |
          python -m pip install --upgrade pip
          # Mengunduh dan memasang paket roda (wheel) biner resmi TA-Lib untuk Linux Ubuntu
          pip install ta-lib
          # Memasang pustaka pendukung untuk keperluan mesin screener lokal Anda
          pip install numpy pandas yfinance requests beautifulsoup4
